name: Minekov
version: '${version}'
main: kimit.minekov.Minekov
api-version: '1.20'
load: POSTWORLD
depend: [NBTAPI]
authors: [ Kimit ]
description: A tarkov-like minecraft bukkit plugin based on skyblock.

commands:
  raidspawn:
    description: Set spawn point when player starts raid.
    usage: /<command> <x> <y> <z>
    permission: minekov.admin.raidspawn
  raid:
    description: Start raid.
    usage: /<command>
    permission: minekov.raid
  receive:
    description: Receive player's item.
    usage: /<command>
    permission: minekov.receive
  market:
    description: Open market.
    usage: /<command>
    permission: minekov.market.market
  sell:
    description: Register item to market.
    usage: /<command>
    permission: minekov.market.sell
  getgold:
    description: Get player's gold.
    usage: /<command> <player>
    permission: minekov.admin.getgold
  setgold:
    description: Set player's gold.
    usage: /<command> <player> <gold>
    permission: minekov.admin.setgold
  gold:
    description: Give player gold.
    usage: /<command> <gold>
    permission: minekov.gold
  lootitem:
    description: Give player a random looting item.
    usage: /<command>
    permission: minekov.admin.lootitem