name: Minekov
version: '${version}'
main: kimit.minekov.Minekov
api-version: '1.20'
load: POSTWORLD
depend: [NBTAPI]
authors: [ Kimit ]
description: A tarkov-like minecraft bukkit plugin based on skyblock.

commands:
  spawn:
    description: Set spawn point of raid.
    usage: /<command> <x> <y> <z>
    permission: minekov.admin.spawn
  escape:
    description: Set escape point of raid.
    usage: /<command> <x> <y> <z>
    permission: minekov.admin.escape
  loot:
    description: Set looting point of raid.
    usage: /<command> <x> <y> <z>
    permission: minekov.admin.loot
  raid:
    description: Start raid.
    usage: /<command>
    permission: minekov.raid
  getgold:
    description: Get player's gold.
    usage: /<command> <player>
    permission: minekov.admin.getgold
  setgold:
    description: Set player's gold.
    usage: /<command> <player> <gold>
    permission: minekov.admin.setgold
  gold:
    description: Give player gold.
    usage: /<command> <gold>
    permission: minekov.gold
  lootitem:
    description: Give player a random looting item.
    usage: /<command>
    permission: minekov.admin.lootitem
  lootchest:
    description: Place looting chests.
    usage: /<command>
    permission: minekov.admin.lootchest
  receive:
    description: Receive player's item.
    usage: /<command>
    permission: minekov.receive
  market:
    description: Open market.
    usage: /<command>
    permission: minekov.market.market
  sell:
    description: Register item to market.
    usage: /<command>
    permission: minekov.market.sell
  shop:
    description: Open shop.
    usage: /<command>
    permission: minekov.shop
  mob:
    description: Set mob spawn area.
    usage: /<command> <first|last> <x> <y> <z>
    permission: minekov.admin.mob
  initializer:
    description: Set RaidInitializer true or false.
    usage: /<command> <true|false>
    permission: minekov.admin.initializer
